# BTC1889 - Deep Learning Team Project
# Authors: Kimberly Corniel, Trinley Palmo, Youssef Emam
# Date: Mar. 31st 2025

# Notes: To run the script ensure the following files are in the same (working directory):
  # main.R (This file)
  # Corona_NLP_test.csv
  # Corona_NLP_train.csv


#### Library Calls and Function Definitions ####

library(keras)
library(tidyverse)
library(ggplot2)


#### C2.1 Importing the data ####

#setting the working directory
setwd(getwd())

# importing the data

training_data <- read.csv("Corona_NLP_train.csv")
testing_data <- read.csv("Corona_NLP_test.csv")

#shuffling data
indicies <- sample(nrow(training_data))
training_data <- training_data[indicies,]

#shuffling testing data
indicies <- sample(nrow(testing_data))
testing_data <- testing_data[indicies,]


#Distribution of sentiments looks reasonably balanced
training_labels <- training_data$Sentiment

ggplot(data.frame(Sentiment = training_labels), aes(x = Sentiment, fill = Sentiment))+
  geom_bar()+
  labs(
    y = "Count",
    title = "Class Distribution"
  )+
  theme(
    plot.title = element_text(hjust = 0.5)
  )


# Pulling the labels, one-hot encoding
training_labels <- training_data$Sentiment %>% 
  as.factor()

#need to zero index to use the to_categorical function
training_labels <- (as.numeric(training_labels)-1) %>% 
  to_categorical()

testing_labels <- testing_data$Sentiment %>% 
  as.factor()

testing_labels <- (as.numeric(testing_labels)-1) %>% 
  to_categorical()

#Isolating the tweets
training_data <- training_data$OriginalTweet
testing_data <- testing_data$OriginalTweet

summary(training_data)
summary(testing_data)

summary(training_labels)
summary(testing_labels)

#### C2.2 Preprocessing Text and labels ####

# Replace invalid characters with blanks
training_data <- iconv(training_data, from = "UTF-8", to = "UTF-8", sub = "")
testing_data <- iconv(testing_data, from = "UTF-8", to = "UTF-8", sub = "")


#find the lengths of all tweets
lengths <- nchar(training_data)

#Distribution of lengths
summary(lengths)

#pick the 90th percentile to pad to
# this covers most sequences, but will exclude any outliers
max_length<- quantile(lengths, 0.9)

#use the 10000 most common words
max_features <- 10000

#Tokenizing training data
tokenizer <- text_tokenizer(num_words = max_features) %>%
  fit_text_tokenizer(training_data)

training_sequences <- texts_to_sequences(tokenizer, training_data)


#Tokenizing testing data

testing_sequences <- texts_to_sequences(tokenizer, testing_data)

#padding sequences
training_data <- pad_sequences(training_sequences, maxlen = max_length)
testing_data <- pad_sequences(testing_sequences, maxlen = max_length)


#### C2.3 ####

# Tuning

if (F){
  # Hyperparameter grids to search
  hidden_units_grid <- c(128, 256, 512)
  output_dims <- c(32, 64, 128)
  batch_sizes <- c(32, 64)
  
  tuning_results <- list()  # store results
  
  #Set variables to hold temp resutls
  best_acc <- 0
  best_config <- NULL
  
  counter <- 1
  
  for (units in hidden_units_grid) {
    for (dim in output_dims) {
      for (bs in batch_sizes) {
          
        cat(sprintf("\n=== Training model %d with units=%d, output dim=%.4f, batch_size=%d ===\n",
                    counter, units, dim, bs))
        
        # Define the model
        model <- keras_model_sequential() %>%
          layer_embedding(input_dim = max_features, output_dim = 8, input_length = max_length) %>%
          layer_flatten() %>%
          layer_dense(units = units, activation = "relu") %>%
          layer_dense(units = 5, activation = "softmax")
        
        # Compile using SGD with custom lr and momentum
        model %>% compile(
          optimizer = "rmsprop",
          loss = "categorical_crossentropy",
          metrics = c("accuracy")
        )

        # Fit the model
        history <- model %>% fit(
          training_data,
          training_labels,
          epochs = 5,        # set fewer epochs while searching
          batch_size = bs,
          validation_split = 0.2,
          verbose = 0        # make it silent for easier reading
        )
        
        # Extract final validation accuracy
        val_acc <- tail(history$metrics$val_accuracy, 1)
        cat(sprintf("Final val_accuracy: %.4f\n", val_acc))
        
        # Save results
        tuning_results[[counter]] <- list(
          units      = units,
          output_dim = dim,
          batch_size = bs,
          val_acc    = val_acc
        )
        
        # Keep track of best result
        if (val_acc > best_acc) {
          best_acc <- val_acc
          best_config <- tuning_results[[counter]]
        }
        
        #add one to the counter
        counter <- counter + 1
        
      }
    }
  }
  
  tuning_results[["best_config"]] <- best_config
  save(tuning_results, file = "tuning_results2.RData")
}




# Load Data file generated by creating hyperparameter grid and finding best results
# This was done with the same code as above but with the SGD optimizer
load("tuning_results.RData")
tuning_results$best_config

#This was done with the rmsprop optimizer - better validation accuracy
load("tuning_results2.RData")
tuning_results$best_config

#unpack results
c(units, output_dim, batch_size, val_acc) %<-% tuning_results$best_config
# 256 units in the hidden layer
# 128 for the output dimension of the embedding layer
# Batch size of 32


#Use to train the model
model <- keras_model_sequential() %>%
  #embedding layer
  layer_embedding(input_dim = max_features, output_dim = 8, input_length = max_length) %>%
  #flattening
  layer_flatten() %>%  
  #One hidden layer
  layer_dense(units = 512, activation = "relu") %>% 
  #output layer
  layer_dense(units = 5, activation = "softmax")

model

#Compiling the model
model %>% compile(
  optimizer = "rmsprop",
  loss = "categorical_crossentropy",
  metrics = c("acc")
)

#training the model
history <- model %>% fit(
  training_data,
  training_labels,
  epochs = 10,
  batch_size = 32,
  validation_split = 0.2
)

perf <- evaluate(model, testing_data, testing_labels)
perf



